### ISSUE TITLE
关于本地查询地址改为查询服务器的方法

### ISSUE THREAD

**Issue by Lianging** [chihane/JDAddressSelector#1]
你好，我找了这样的地址选择器很久，写得很好，谢谢作者。
建议：
  selectProvinces()
  selectCitiesBy(int i)
  selectCountiesBy(int i)
  selectStreetsBy(int i)
这几个方法提供除了查询本地数据库的方法外，另外提供自定义的查询方法就更好了（我想查询服务器），目前我是下载工程到本地，然后倒入library，把上面的方法从private改为public，然后子类复写上面的方法实现自己要的查询的。
我是有一点少经验的开发者，如有错漏点，欢迎指教。再次感谢你的贡献，谢谢。

**Comment by chihane** [comment]
感谢反馈。
我本来打算做成和京东一模一样的样子，所以完全没有考虑过可扩展性，连字符串都是直接写死的，数据也是京东原版数据。
但是居然真的有人用……有点感动……
后面几个版本我适当开放一些内容的自定义吧。
谢谢建议啦，很有建设性 :)
