### ISSUE TITLE
打包混淆之后出错了

### ISSUE THREAD

**Issue by GongZiZhang** [chihane/JDAddressSelector#10]
报chihane.jdaddressselector.b.g is not registered with a Database. Did you forget the @Table annotatio

**Comment by chihane** [comment]
就不要混淆了吧，这种基于编译时注解的代码一般是要排除在外的。

在项目的 proguard-rules 文件里加上：

```
-keep class chihane.jdaddressselector.** { *; }
```

为了以防万一， DBFlow 的最好也加上：

```
-keep class com.raizlabs.android.dbflow.** { *; }
```

**Comment by GongZiZhang** [comment]
这样混淆好像也没用，是DefaultAddressProvider打开数据库的时候报错了，因为我用的是自己后台的数据，所以直接没用DefaultAddressProvider，使用了自己写的AddressProvider，如此一来就没问题了
