### ISSUE TITLE
有个BUG

### ISSUE THREAD

**Issue by rmtic** [chihane/JDAddressSelector#14]
比如：
第一次我选中 Provinces；
下一步，我选city;
按理说，只有选择的未红色字体和勾选，但是其他没被选的也变成了红色字体。

**Comment by rmtic** [comment]
用空修复一下呗，挺好用的

**Comment by chihane** [comment]
没看懂，需要详细描述一下问题

是不是 City 没有分别设置 ID 的问题？

**Comment by rmtic** [comment]
我的数据：
香港島
香港島 香港仔 香港香港仔湖北街12號裕景中心9樓1室
香港島 香港仔 香港香港仔湖北街12號裕景中心9樓1室
香港島 香港仔 香港香港仔湖北街12號裕景中心9樓1室

九龙
九龙地址1。。。。。。。。。
九龙地址2。。。。。。。。。
--------------------------------------------------------------
就是自定义了一个AddressSelector,这里我只需要两个数据，所以counties和streets 我都没用，就send(null),不知道这个会不会影响使用；
selector.setAddressProvider();里面
1. provideProvinces()，addressReceiver.send(provinces);
2. provideCitiesWith()，addressReceiver.send(citys); 我有判断ID
3.provideCountiesWith,addressReceiver.send(null);
4.provideStreetsWith ,addressReceiver.send(null);
因为我只有两种数据

问题：当我选中某个city后，选中的city变成了勾选和红色字体，但是为什么没被选中的也变红了（原来字体颜色是黑色）

**Comment by chihane** [comment]
https://github.com/chihane/JDAddressSelector/blob/master/library/src/main/java/chihane/jdaddressselector/AddressSelector.java#L628

**Comment by chihane** [comment]
列表项的选中状态是通过数据的 ID 判断的： [参考源码](https://github.com/chihane/JDAddressSelector/blob/master/library/src/main/java/chihane/jdaddressselector/AddressSelector.java#L628)

如果列表中有多个 ID 相同的数据项，选中一个之后就会同时标记其他几个
即使几个 City 名称相同，也需要给它们分配不同的 City.id

不知道我有没有理解错

**Comment by rmtic** [comment]
你说对了，City.id 我确实没赋值给他。还有个问题，假设我的数据是来源3个接口，每点一次都需要请求不同接口，我怎么刷新数据

**Comment by chihane** [comment]
合并网络请求是编码范畴的问题了

可以在新线程里依次执行网络请求，拿到结果后拼接，或者使用 RxJava 之类的工具

数据的来源 AddressSelector 是不关心的，只要拼接好数据之后统一发送给 addressReceiver 就行了
