### ISSUE TITLE
自定义地址怎么实现不了

### ISSUE THREAD

**Issue by sunshinewei** [chihane/JDAddressSelector#15]

**Comment by chihane** [comment]
需要具体描述一下你遇到的问题

**Comment by sunshinewei** [comment]
自定义地址省份我无法添加自己的地址.
`public class LawAddressDataSourece implements AddressProvider {
    @Override
    public void provideProvinces(final AddressReceiver<Province> addressReceiver) {
      
            SourceFactory.create()
                    .homeAreas("")
                    .observeOn(AndroidSchedulers.mainThread())
                    .subscribeOn(Schedulers.io())
                    .subscribe(new BaseSubcriber<AreaBean>() {
                        @Override
                        public void onNext(AreaBean bean) {
                            if (bean != null) {
                          
                                List<AreaBean.DataBean> data = bean.getData();
                                List<Province> provinces = new ArrayList<Province>();
                                for (int i = 0; i < data.size(); i++) {
                                    Province province = new Province();
                                    AreaBean.DataBean dataBean = data.get(i);
                                    province.name = dataBean.getAreaName();
                                    province.id = dataBean.getAreaId();
                                    provinces.add(province);
                                }
                      
                                addressReceiver.send(provinces);
                            }
                        }
                    });
    }

    @Override
    public void provideCitiesWith(int i, final AddressReceiver<City> addressReceiver) {
    
        SourceFactory.create()
                .homeAreas("i")
                .observeOn(AndroidSchedulers.mainThread())
                .subscribeOn(Schedulers.io())
                .subscribe(new BaseSubcriber<AreaBean>() {
                    @Override
                    public void onNext(AreaBean bean) {
                        if (bean != null) {
                            List<AreaBean.DataBean> data = bean.getData();
                            List<City> cities = new ArrayList<City>();
                            for (int i = 0; i < data.size(); i++) {
                                City city = new City();
                                AreaBean.DataBean dataBean = data.get(i);
                                city.id = dataBean.getAreaId();
                                city.name = dataBean.getAreaName();
                                city.province_id = dataBean.getParentId();
                                cities.add(city);
                            }
                            addressReceiver.send(cities);
                        }

                    }
                });
    }

    @Override
    public void provideCountiesWith(int i, final AddressReceiver<County> addressReceiver) {
        SourceFactory.create()
                .homeAreas(i + "")
                .subscribeOn(Schedulers.io())
                .observeOn(AndroidSchedulers.mainThread())
                .subscribe(new BaseSubcriber<AreaBean>() {
                    @Override
                    public void onNext(AreaBean bean) {
                        if (bean != null) {
                            List<County> counties = new ArrayList<County>();
                            List<AreaBean.DataBean> data = bean.getData();
                            for (int i = 0; i < data.size(); i++) {
                                County county = new County();
                                AreaBean.DataBean dataBean = data.get(i);
                                county.city_id = dataBean.getParentId();
                                county.id = dataBean.getAreaId();
                                county.name = dataBean.getAreaName();
                                counties.add(county);
                            }
                            addressReceiver.send(counties);
                       
                        }
                    }
                });
    }

    @Override
    public void provideStreetsWith(int i, final AddressReceiver<Street> addressReceiver) {
        SourceFactory.create()
                .homeAreas(i + "")
                .subscribeOn(Schedulers.io())
                .observeOn(AndroidSchedulers.mainThread())
                .subscribe(new BaseSubcriber<AreaBean>() {
                    @Override
                    public void onNext(AreaBean bean) {
                        if (bean != null) {
                            List<Street> streets = new ArrayList<Street>();
                            List<AreaBean.DataBean> data = bean.getData();
                            for (int i = 0; i < data.size(); i++) {
                                Street county = new Street();
                                AreaBean.DataBean dataBean = data.get(i);
                                county.county_id = dataBean.getParentId();
                                county.id = dataBean.getAreaId();
                                county.name = dataBean.getAreaName();
                                streets.add(county);
                            }
                            addressReceiver.send(streets);
                        
                        }
                    }
                });
    }
}
`
添加不了,麻煩你了.

**Comment by sunshinewei** [comment]
city,county可以.

**Comment by chihane** [comment]
首先提供城市的方法里接口参数写错了
```.homeAreas("i")```
字符串不是这么格式化的

其次最好先检查一下你接口的返回，比如 onNext 方法有没有调用到，bean 参数是不是空的

**Comment by sunshinewei** [comment]
那我給你發錯了,沒有執行到這個方法中:
`public void provideProvinces(final AddressReceiver addressReceiver) {}`
我打印看是,不知道爲什麼.

**Comment by chihane** [comment]
用 `selector.setAddressProvider()` 把你自定义的 Provider 设置好了么？

**Comment by sunshinewei** [comment]
這樣設置的:
`AddressSelector selector = new AddressSelector(this);
        selector.setAddressProvider(new LawAddressDataSourece());
        View view = selector.getView();
        mAddress.addView(view);`

**Comment by chihane** [comment]
那 city 和 county 可以是什么意思？

**Comment by sunshinewei** [comment]
添加城市和城镇可以实现,但是添加省份那个方法不执行,不知道为什么.

**Comment by chihane** [comment]
没有省份的话 city 和 county 是怎么执行到的？

**Comment by sunshinewei** [comment]
省份是默认的,没有执行网络请求这块,这个方法没有执行.

**Comment by chihane** [comment]
那我明白了，但是这是个已经修复了的 bug 啊
https://github.com/chihane/JDAddressSelector/commit/0f3804fedd970dc8a5e36096dc531fe564eea1c7

确认一下库的版本号，如果是 1.1.4 的话麻烦看一下 `setAddressProvider()` 方法的源码里有没有 `retrieveProvinces();` 这么一行

否则升级到 1.1.4 应该就能解决这个问题

**Comment by sunshinewei** [comment]
噢噢，我一会看一下，谢谢大神了
