### ISSUE TITLE
BottomDialog设置自定义json数据

### ISSUE THREAD

**Issue by lockonD** [chihane/JDAddressSelector#26]
如果 让BottomDialog设置成自定义的json数据

**Comment by chihane** [comment]
duplicate #24 
refer: [document](https://github.com/chihane/JDAddressSelector#%E4%BD%BF%E7%94%A8%E8%87%AA%E5%AE%9A%E4%B9%89%E6%95%B0%E6%8D%AE%E6%BA%90)
