### ISSUE TITLE
请问下这里面的数据源是从哪儿来的？

### ISSUE THREAD

**Issue by huzipiaopiao** [chihane/JDAddressSelector#27]
看源码找了很久，没找到数据源是哪儿来的，只知道一触发BottomDialog就会生成一个数据库，但是不知道数据是从哪儿来的，请指点一下

**Comment by yecaler** [comment]
请认真查看源码！

**Comment by yecaler** [comment]
![default](https://user-images.githubusercontent.com/25024969/46199844-ad723100-c342-11e8-8e8f-e7ec1cd10698.png)

**Comment by huzipiaopiao** [comment]
看到了，谢谢，我直接远程依赖的，找了一圈没有找到数据库，忘记直接看库项目了
