### ISSUE TITLE
您好，请问怎么修改主题色

### ISSUE THREAD

**Issue by mikezhang3679** [chihane/JDAddressSelector#28]
![image](https://user-images.githubusercontent.com/15795338/40695557-4c55cd26-63f4-11e8-8277-6cebf51cc083.png)

**Comment by longalei** [comment]
这个项目目前不支持修改主题色。只有自己clone下来进行修改

**Comment by sunshinewei** [comment]
看源代码这个TextView是public,可以拿出来修改字体颜色

**Comment by chihane** [comment]
dup #21

**Comment by marren06** [comment]
@sunshinewei 不能改吧！
