### ISSUE TITLE
使用自定义数据源点击省份没有展示下一级

### ISSUE THREAD

**Issue by Android4Wang** [chihane/JDAddressSelector#29]
使用的是本地Json文件数据源

   //使用自定义数据源
        selector.setAddressProvider(object : AddressProvider {
            override fun provideProvinces(addressReceiver: AddressReceiver<Province>) {
                addressReceiver.send(AddressUtil().getProvinces(this@AddSiteActivity))
            }

            override fun provideCitiesWith(provinceId: Int, addressReceiver: AddressReceiver<City>) {
                addressReceiver.send(AddressUtil().getCity(provinceId, this@AddSiteActivity))
            }

            override fun provideCountiesWith(cityId: Int, addressReceiver: AddressReceiver<County>) {
                addressReceiver.send(AddressUtil().getCounty(cityId, this@AddSiteActivity))

            }

            override fun provideStreetsWith(countyId: Int, addressReceiver: AddressReceiver<Street>) {
            }
        })

这样使用，点击省份不显示下一级

**Comment by chihane** [comment]
确认 `AddressUtil().getCity(provinceId, this@AddSiteActivity)` 可以取到数据吗？
没有展示下一级是指？点击了没有反应？spinner 出来了吗？
