### ISSUE TITLE
总体上很不错，就是回到city province等model的没有get方法

### ISSUE THREAD

**Issue by fly7632785** [chihane/JDAddressSelector#3]
个人再提个小建议，可以把回到接口拆分成多个回调方法 ，这样适应新更强。

**Comment by fly7632785** [comment]
还有就是建议给list设置一个最小高度，避免dialog中如果只有1个数据，确定按钮会上移

**Comment by chihane** [comment]
1. 标题没有看懂，是指 `AddressProvider` 没有 getter 方法吗？如果是的话，这是因为这个东西没有理由需要一个 getter 方法
2. 多个回调方法会使得代码非常杂乱，连 lambda 语句都救不了，实际上 `AddressProvider` 现在这个样子已经让我很难受了。能简单地用倒序空值判断处理的问题不应该拆分出多个方法甚至多个类
3. Demo 中没有出现这样的问题，你说的确定按钮是放在哪里的？

**Comment by fly7632785** [comment]
前两个问题  是我多虑了
第三个问题，我的按钮就是dialog的positiveButton nagetiveButton
