### ISSUE TITLE
自定义数据源,接口返回后一直转圈 明明成功了.没有报错.

### ISSUE THREAD

**Issue by njwl434** [chihane/JDAddressSelector#30]
自定义数据源,接口返回后一直转圈 明明成功了.没有报错. 还有为什么id,province_id 全定义的int类型呢.心好累

**Comment by chihane** [comment]
有调用 `receiver.send` 设置数据么，调用后进度条应该就会消失

**Comment by njwl434** [comment]
addressReceiver.send(list);  调用了,还是没有.打断点已经返回了.不过我把所有int全换成long了 @chihane

**Comment by njwl434** [comment]
可以了addressReceiver.send(list)  list没有值...
