### ISSUE TITLE
可以选择第一层，请求网络数据刷新第二层吗

### ISSUE THREAD

**Issue by 542604974** [chihane/JDAddressSelector#36]
可以选择第一层，请求网络数据刷新第二层吗

**Comment by chihane** [comment]
参看文档 [使用自定义数据源](https://github.com/chihane/JDAddressSelector#%E4%BD%BF%E7%94%A8%E8%87%AA%E5%AE%9A%E4%B9%89%E6%95%B0%E6%8D%AE%E6%BA%90) 一节

继承 DefaultAddressProvider，保留原有的 provideProvinces 方法实现，覆写其余方法即可
