### ISSUE TITLE
自定义数据源无效

### ISSUE THREAD

**Issue by fg2q1q3q** [chihane/JDAddressSelector#6]
你好，按照readme中尝试自定义数据，发现省份数据设置无效
经查证，是因为setAddressProvider方法并没有进行省份数据源刷新，已修正内容如下：
`public void setAddressProvider(AddressProvider addressProvider) {

        this.addressProvider = addressProvider;

        if (addressProvider == null) {

            this.addressProvider = DEFAULT_ADDRESS_PROVIDER;

        }
         retrieveProvinces();//增加该行重新赋值
    }`

**Comment by Lsy1992** [comment]
果然有用，我这边也是发现设置了自定义的数据后，省这一行还是默认的

**Comment by fg2q1q3q** [comment]
@Lsy1992 是的，因为源码中setAddressProvider方法只是设置了provider，但是省份的data数据在设置之前就已经赋值了，设置之后没有重新赋值。另外建议作者自定义的bottomdialog最好也暴露一下setAddressProvider的方法，同时对于文字颜色、大小、分割线、dialog默认高度等作为可配置项允许个性化定制

**Comment by Lsy1992** [comment]
@fg2q1q3q  请问你添加自定义数据源是使用什么样的格式呢？ 是多级嵌套的JSON数组吗？

**Comment by fg2q1q3q** [comment]
@Lsy1992 理论上来说确实是实体嵌套list实体，不过由于我的业务场景不同，所以我的数据都是从数据库中过滤查询出来的

**Comment by Lsy1992** [comment]
为何你的issuse还没被作者关闭？O(∩_∩)O

**Comment by chihane** [comment]
因为最近在忙，没有时间改代码。

@fg2q1q3q 既然是复制的代码，如果能采用 fork 方式并 PR 回来的话就太感谢了。

**Comment by fg2q1q3q** [comment]
@chihane 说来见笑，虽然fork过很多次，但是PR还从来没弄过不太会-_-|||，我主要是要用在自己项目中，所以copy了一份除了修复这个问题外会稍微修改一些细节用以符合自己app的外观和逻辑，不具有通用性，因此也就没有递交分支（主要是不会递交o(╯□╰)o）

**Comment by chihane** [comment]
修复了，感谢 @fg2q1q3q 提醒。

0f3804fedd970dc8a5e36096dc531fe564eea1c7

另外发布了一个新的小版本 1.1.4 。

**Comment by chihane** [comment]
另外 `BottomDialog` 源码很简单，名字起得也很随意，初衷只是提供一个便捷的调用方法，要修改样式的话重新写一个会比较方便。
