### ISSUE TITLE
在onAddressSelected方法中获取到的城市ID不对啊

### ISSUE THREAD

**Issue by Lsy1992** [chihane/JDAddressSelector#8]
city.id 这里面的值查询不到城市啊

**Comment by chihane** [comment]
能详细描述一下问题吗？

`city.id` 应该是用来查询下一级地址的

**Comment by Lsy1992** [comment]
上传到接口的时候 要求传省ID、市ID、区ID、这样的。。 
APP中实际使用场景保存地址也不可能是这个String啊，肯定要以ID为准

**Comment by chihane** [comment]
如果需要用自己的接口，那就需要提供自定义的 AddressProvider 以提供自定义的地址，默认地址的 ID 值来自京东，并不是什么国家标准，自然是不能通用的。

**Comment by Lsy1992** [comment]
setAddressProvider（ ） 中的provideCitiesWith一定要用子线程设置数据吗？

**Comment by chihane** [comment]
加了 AddressReceiver 是为了支持异步调用，同步的自然也是可以的，可以参考 [Readme](https://github.com/chihane/JDAddressSelector/blob/master/README.md#使用自定义数据源) 中的示例代码。

**Comment by Lsy1992** [comment]
![gvctx2mdt 2lv9fula d6c](https://cloud.githubusercontent.com/assets/12758497/20961961/50ffd7ae-bca2-11e6-9ab2-38813ccf9ae6.jpg)   **Readme 中的示例代码** 像天书，没太看明白，需要什么样的数据结构？意思必须要分开3个数组来表示省市区？ 额，最好能来一个自定义的demo...

**Comment by chihane** [comment]
示例代码为了表示可选方式很多才分成了三种方式发送结果，实际上只要能取到地址 `List` 并发送给 `AddressReceiver` ，用什么方式获取数据都是可以的。

**Comment by Lsy1992** [comment]
(⊙o⊙)哦，我动手试试吧，麻烦再看下我另外一个问题，就是关于这个滑动效果的
