### ISSUE TITLE
【建议】能否增加一个打开地址选择时，默认选中的为上一次结果?

### ISSUE THREAD

**Issue by Lsy1992** [chihane/JDAddressSelector#9]
例如京东APP中：编辑地址-所在地区 已经有数据了： 北京市 - 海淀区 - 某街道
这时再次点击编辑后弹出的框是默认选中已选的了。。。这个可以做吗？

**Comment by chihane** [comment]
目前的结构不太容易实现，fork 了修改代码吧。
